apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
# Command to create secret password
# past below command in terminal
# echo -n 'root' | base64
