version: "3"
services:
  mysql:
    image: "mysql:latest"
    container_name: mysqldb
    ports:
      - "3307:3306"

    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: djangoDb
    volumes:
      - "mysql-data:/var/lib/mysql"

  backend:
    image: "satyambrother/student-registration-crud-project:01"
    container_name: student_reg
    ports:
      - "8000:8000"
    networks:
      - my-network
    environment:  
      MYSQL_HOST: mysql
      MYSQLDB_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  my-network:
         external: true
