apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod
spec:
  containers:
    - name: student-reg
      image: satyambrother/student-registration-crud-project:latest
      env:
      - name: MYSQL_HOST
        value: "10.98.19.211"  
      ports:
        - containerPort: 8000
      imagePullPolicy: Always
