apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app-deployment
  labels:
    app: two-tier-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: student-reg
          image: satyambrother/student-registration-crud-project:02
          env:
            - name: MYSQL_HOST
              value: "10.98.19.211" 
            - name: MYSQLDB_PASSWORD
              value: "root"  
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
